services:
  api: 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    restart: always
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis:latest 
    container_name: redis
    ports:
      - "6379:6379"  
    volumes:
      - redis_data:/data  
    restart: always  

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"  
    volumes:
      - ./www:/usr/share/nginx/html
      - ./etc/nginx.conf:/etc/nginx/nginx.conf
    restart: always  
    depends_on:
      - api


volumes:
  redis_data:
