services:

  api: 
    image: ghcr.io/kirkegaard/go-grid:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: api
    restart: always
    ports:
      - "6060:6060"
    environment:
      - GRID_PORT=6060
      - GRID_SIZE=625
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis:latest 
    container_name: redis
    ports:
      - "6379:6379"  
    volumes:
      - redis_data:/data  
    restart: always  

volumes:
  redis_data:
