name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'  # Match version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/go-grid:${{ github.ref_name }}
          ghcr.io/${{ github.repository }}/go-grid:latest

    - name: Clean up old tags
      run: |
        docker image prune -f --filter "until=24h"
